# Generated by Django 4.1.2 on 2022-11-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.CharField(max_length=30)),
                ('IIN', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('middlename', models.CharField(max_length=30)),
                ('bloodgroup', models.CharField(max_length=30)),
                ('emergencycontactnumber', models.CharField(max_length=30)),
                ('contactnumber', models.CharField(max_length=30)),
                ('departmentID', models.CharField(max_length=30)),
                ('specaliztionID', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='')),
                ('addres', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('priceoftheappointment', models.CharField(max_length=30)),
                ('scheduledetails', models.CharField(max_length=30)),
                ('degree', models.CharField(max_length=30)),
                ('rating', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.CharField(max_length=30)),
                ('IIN', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('middlename', models.CharField(max_length=30)),
                ('bloodgroup', models.CharField(max_length=30)),
                ('emergencycontactnumber', models.CharField(max_length=30)),
                ('contactnumber', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('addres', models.CharField(max_length=30)),
                ('maritalstatus', models.CharField(max_length=30)),
                ('registrationdate', models.CharField(max_length=30)),
                ('optionaldetails', models.CharField(max_length=30)),
            ],
        ),
    ]
