# Generated by Django 4.1.2 on 2022-11-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
