# Generated by Django 4.1.2 on 2022-12-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Pending...', max_length=30),
        ),
    ]
